### ISSUE TITLE
No such file or directory: 'assets/web-dsl-mapping.json'

### ISSUE THREAD

**Issue by etienne-dev-tools** [samuelmat19/image2source-tf2#4]
Hi there,
I am excited to try your model for my own application.

I am trying to reproduce your basic setup and make it train with the pix2pix dataset but in creating the dataset i have the error below. It looks like the tokenizer was not checked in ?

if I get the pretrained_weights.xz file linked in description and use datasets/pix2code_tokenizer.json it says it's missing opening-tag

```
 find ../pix2code/datasets/web/all_data/ -name *.gui | xargs -n1 ./compiler/web-compiler.py
Traceback (most recent call last):
  File "/Users/etienne/sdk/code/research/image_to_testcase/image2source-tf2/./compiler/web-compiler.py", line 25, in <module>
    compiler = Compiler(dsl_path)
  File "/Users/etienne/sdk/code/research/image_to_testcase/image2source-tf2/compiler/classes/Compiler.py", line 10, in __init__
    with open(dsl_mapping_file_path) as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'assets/web-dsl-mapping.json'
```

**Comment by etienne-dev-tools** [comment]
I found the file in the pix2pix repo
https://github.com/tonybeltramelli/pix2code/blob/master/compiler/assets/web-dsl-mapping.json
